# Generated by Django 2.2.6 on 2019-10-14 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Stock', '0003_auto_20191014_1939'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalle_compra',
            options={'ordering': ['id'], 'verbose_name': 'Detalle de Compra', 'verbose_name_plural': 'Detalle de Compras'},
        ),
    ]
