# Generated by Django 2.2.6 on 2019-10-14 23:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Stock', '0003_auto_20191014_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=datetime.datetime(2019, 10, 14, 20, 0, 38, 702859))),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Stock.Producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Ventas.Venta')),
            ],
        ),
    ]
