# Generated by Django 2.2.6 on 2019-10-14 23:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0002_auto_20191014_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 14, 20, 4, 30, 888139)),
        ),
    ]
