# Generated by Django 2.2.5 on 2019-10-15 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0003_auto_20191014_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 15, 9, 21, 18, 125330)),
        ),
    ]
